name: build toplevel and push to cachix

on: [push, pull_request]

jobs:
  jobs:
  build_and_push_toplevel:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v14
        with:
          name: rcmast3r
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#nixosConfigurations.tcu.config.system.build.toplevel --accept-flake-config
      - run: nix-store -qR --include-outputs $(nix-store -qd $(./result)) | grep -v '\.drv$' | cachix push rcmast3r
