name: Release SDImage weekly

on:
  schedule:
    - cron: '1 1 * * 1' # https://crontab.guru/#1_1_*_*_1 run weekly on monday
  
  workflow_dispatch:

jobs:
  build_image_and_top_level:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix build .#nixosConfigurations.tcu.config.system.build.sdImage --accept-flake-config

      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H_%M_%S')"

      - name: Release weekly sd image
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.date.outputs.date }}
          files: |
            ./result/sd-image/*.img.zst